[[XZ]]
arch = "aarch64"
git-tree-sha1 = "b7801db3b1dfdd7e22586e15fd2fcd146c1ad1d9"
os = "macos"

    [[XZ.download]]
    sha256 = "ee2bbdcff00ba564c1969729b7f40bd002d79a3fe02941583167480af40f3fec"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "a2d8c82e261ea0712eb7e60b14ce99a3a4486594"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "9c38fbd4c40b5aff40ab38f73d29e98c010372e265d4d244450b79108ba24515"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "eec7b5b03228f4a5493cdef783945a6e7a3ebcbf"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "502e4e9776b9456d58dbcad43a82a3101f43b5e85f107a6ffa58f4da8d7644a4"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "c7abcf66bfffde37cc10122fb87b2c14fddb7110"
os = "freebsd"

    [[XZ.download]]
    sha256 = "5b7715806047556cec542d1989ef2609141853739ccc24da70ee0a0e568d52a8"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.aarch64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "59c6e9ee4e952d12cdd9fd5783f93791d6df0776"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "88d5fec1a270062192ba876eee3684916640a03fb2e970b551e4670b5ebbc97a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82c063860ad0f17e6589867e2390dca9b404804f"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "0429c78edde60f2847095dc49be7998737f6d3fbeaed15216690f5171d6b668f"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a2420a0da883836cf7f745bdc6386b97509075b"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "32cd26246385cc92dfe153cc3519e81703a0a4f05a6e41695f04393ec78cd863"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b57c865d0f540f027074bf1e970dd7700a8783d"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "1203b34f6a2c6e9c54459d2930d99c917aa2327321fb7f15f66f1dc332f1d44b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "7214cb4a2129ae69ded4438a268deaf933011774"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "ba2165204fa73ae56395b6def3f753509439df9e5251bdaf153896a27d2d6d1c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "2e46e99ef40ba5a13416b06c44647583634d4005"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "5cc7e6a5334d95743c90e47d4969c1d156d54730aee7c1a4e0e0663466728ca7"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "6ccbdfc935d5473e4dd9579d80f757d43bb114e1"
os = "windows"

    [[XZ.download]]
    sha256 = "fd9f79d4ab883cda6fd2c56d58907ecfaa8bc51470f5f8e383c74e7a4d85e091"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "2fbedf0b403d35f8704502f3ac00eb5e2a4db622"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "9b730164b64968785c98fd1ea5abc17321ed5a30258203b8a17fe4ed639f8b77"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "riscv64"
git-tree-sha1 = "ef2c80dfdbcb3848c62e68e7dc231786911f8bf0"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "6b0f9a126ad53e0890b273bcf8f8916ff8664bfe5f6c97c8d61a137b43fc9887"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.riscv64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "b9320053cd4a2504e2a066589556a927252e1601"
os = "macos"

    [[XZ.download]]
    sha256 = "4a0d9e82ea2df03eac9d3735de83c7e4fe705b019cb95649fe368cf9e77460e1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "a8e1268c656ea6fde5d44ed188563e21009f8cec"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "cb340a15a9118cddb90c85e73f0dff9f22f0b942aa71826dca29e05c21229d5c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "3ec2788808555897bb235a947e21b2cfd5ebe87c"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "af5dda1e07796bf96af33d3b100048ae15b7246c9017fffd798c4a094930031b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "262e65cc23670952398ce427df9ffaed27eb07dd"
os = "freebsd"

    [[XZ.download]]
    sha256 = "478b0982d6a2e1a181ce9ae5be06f8cee095b18bf1850d921b71b172da174f07"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "95bea43c078a0d3c13cbe72748396593c6ff5c4f"
os = "windows"

    [[XZ.download]]
    sha256 = "d37ef7079d68f799bad1f946b7fd7547459af7080853b236402a8bae5ede0fcd"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.0+0/XZ.v5.8.0.x86_64-w64-mingw32.tar.gz"
