[[XZ]]
arch = "aarch64"
git-tree-sha1 = "9625f3f19b7fe9979e8a2b5c240e12e4ef72a951"
os = "macos"

    [[XZ.download]]
    sha256 = "a67aebfad261040408d113e50f1cc78ec188787363ebd109b3f64321eaf31f5d"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "e0057288be146c670b0a741dd8393a11b41f8a7a"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "592cb6dee166b253c846b79fd83e46eb82bdfb3a23916e0e35f831539421cae9"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "82f986bccfa6c1ec5c5b57f92196f3a156a122db"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "8cdc605e58d59819aad2a9e137a2a77f37bc7d05a1687164dc753ff3d487e885"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ba8cc576a5b9bdd651310d4d3aa621268cedd4c"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "ecbf3788866347f4e7a1ab955327ba2e307807573d5713c4781d51cc0b0c9416"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50c58250e7f553286272d1d9b4cd47416d9f9c33"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "df13b1a795a983855297f42ca4842e0186f6ec9b6bdc5738ad4af4cb37f79630"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1bb269317c2e9d97c2b703f106a439189cd82781"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "5b722ec241a23fef17295db773838eb3b1a6eeae2ca89d87f53d7ae5a3e8e519"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e8a14838f33d4f48c58e853df3b139c54bd6f21c"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "a7240b98bac78f5fd6e08c4c47895cf41dd9de4df886c286d61e37f808979bac"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "fec217e0c62ce171f2a9a2c8683eb5133cfe2840"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "9dc84689ae1f1ca102e8b2b59b4dab482c47e3c874146b4a58a3451e31ea89cf"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "d46d0027bcb2b0714a8fb8c45917a548f226c4e6"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "05ce9485a9677465ef8b16484767894080d1b2e40635465205acfcb3ccf63015"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "aabcb853bfd426831dbe73cd22e4a6d07a2ee420"
os = "windows"

    [[XZ.download]]
    sha256 = "b113fedc8922d1af42c20f0aacc3b87439de52ab5c0b8445a24f0b7559b2f1ab"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "cb23f2b040ae3dab58945b8421a916be3c7d25b8"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "5a2ef68747777fbcfe4c5964131af7b799ec1379706f6a33cabc69648828a3f0"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "44eaca1df5ca2ceae187d097da55cfec1d251be3"
os = "macos"

    [[XZ.download]]
    sha256 = "6962a8967a251fabde58ab484e8bf1c1390994e38ab37dce4d9f5929709788fe"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "47755fa870bd90e8a0ace6e3cce437cb3aa06431"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "85a6e0c533714088f80d1e8c330f697ccf5bc8b3f55af8e1ad5f9e9e7b192dda"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "35feb5838989024b607f18aa749564bac80a0990"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "0bfca01aab43d4509c53cfaf986e4049c6b6c8538c786e38b2bfbb1aa98f81ee"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "b4e1060c9fde483f75161592a2ee04d43b2ed4ca"
os = "freebsd"

    [[XZ.download]]
    sha256 = "5be355d73a2d601fb85b1440dae8a22e80f03103e1d19bdb82d1da23e5d7be37"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "fb5110422717b9e2d19f0309e9be69e3d0245c33"
os = "windows"

    [[XZ.download]]
    sha256 = "e57abd129487b770c7e328042ed10331c82e8836bacb05b28105d0d481c849cb"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.5+1/XZ.v5.2.5.x86_64-w64-mingw32.tar.gz"
