[[XZ]]
arch = "aarch64"
git-tree-sha1 = "8f5f66cdbf511f7192128eedfe66211271783733"
os = "macos"

    [[XZ.download]]
    sha256 = "1b7d9111c62eaae7f346bffe22d2de1d547cbbe317a5af320310fa6503435333"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "bbf7a969bf97d658b6b95ada7ea51e55c2f28ec7"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "8f2e94766be8be92b5632dfe9098be5a798fd680b61f67720a34c190e51a5850"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "02d5e00b36eb4cd8f1424a2481f52443230245f4"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "57dc2fc226cd15380de1aba65e0e634cba7c625abf8983a61208893c3d567cb1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fb0ef3bbfb975490529cea07adb509958ccb6af"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "9cd23b370f02c7e8b282d54e0ec372da9fdb0831bf247bc25cbe8abaaa7a1bc8"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff5cbbe781f47f7b4bf7054225cb5c4e814aad70"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "98a258451492e4538904133e883f0648ee39658f06d930492a4fd13414249326"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d753b7312c39228bf82350bf638689fa97570789"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "614e0e7698328f6d1774556e813ae39489b6ebdaf10c47a8762e94d253ded890"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e0f9714a4bc2e2d4ab4e286a7d5200f92199d23"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "a615abde6db2d1f09852be91cbd54c8ae0f0dd1a5074c6d6d82d26a22fc8744c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "d86bf1e19d0c269d50728dace5aecb088d760a6f"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "8f6796d6886efaf9ef0eb7297342e79ee687e77f1e063554f15ba20a256c67a6"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "50ae9949efd1d7f841dfc19f0c2658ff185c17f3"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "70c454bc871f9110fd253b6f316b9275f957544f62422f40d65b088818244b9c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "e6da5fa9f9373f72a9db99f10dd38274d72c8b5b"
os = "windows"

    [[XZ.download]]
    sha256 = "4be4be0b2f1d68d7e6d88a7d79a9e881398c531abcd816714843452811e71002"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "4e56ed43b1a6f9e15fe60b41281764448f8f8fab"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "d1e7ffa586ad9d26f056ce9c5128a8932ea40ac31df8aab304def143b76e64f1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "fcce09ea10f6f2d6e185d17a8123a0054d18c1b4"
os = "macos"

    [[XZ.download]]
    sha256 = "9991861f02fe94114043a417eccfae8debe34db3a00d306b8bacb383612211ff"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "92aadd271e03449550c39ff647722e9472790eef"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "3463949a88d197e6c51357a9261f53b3a6d7c49662eb07b4b51fd05d02ce24ff"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "fbc04fb1a5c7ec4643c7f62b4c73f639e5e774bc"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "dc75ad92ca801ac97a4ff8b01d0a250bba010cba1e77490965507c4d015df6b1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "f673dc85b4c7742f922b1b6c35e4fee907d938cd"
os = "freebsd"

    [[XZ.download]]
    sha256 = "ae3249da201e9d1bed50a03553822e19c7ebadcfefa42d51bc00a900dbae9c4e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "bb0b6bd0a87b767941650cd416487715f4f35502"
os = "windows"

    [[XZ.download]]
    sha256 = "e367bcda109baa375cdc6520196ff04dcfd8f791b6544739ed6934877601b739"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.5+0/XZ.v5.4.5.x86_64-w64-mingw32.tar.gz"
