[[XZ]]
arch = "aarch64"
git-tree-sha1 = "4ed6227ff66b34dcd65f011ad8b91bdf545ac4d8"
os = "macos"

    [[XZ.download]]
    sha256 = "0243bcd9e3b93af669b80b627a5fcab1e027a6c92491567eef5ebe232a969f3a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "e7ecc8fe749ddf6700e0a234a109879b5aa545ac"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "fbf0b60b65ee09dc7dbfae84001d2dc417ba52ea7cfb04947da24b81018cf690"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "7a9c919e37914413c0e12c9322c0f85cfb947b77"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "7486a4f2dbd65caef07a525967a4b300830b43ff899f9d380e9860b638ff7479"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "edd871395219afba2a1f8a9e26334bcee587cd8a"
os = "freebsd"

    [[XZ.download]]
    sha256 = "12139cae3f9a3bc5933204ea728e82c3c61df8b765fe5704448ca83cfc0f24fb"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.aarch64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27c6d8ffa0ccf485bfcc2129fe751c80c0b18433"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "89bbbc9f1b2cad12162361fd6d49a75cc384221a6c931f94ba84aff7d648d3fc"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e90f2d2b543e4d1f83ce30da1faae38079a6403"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "49c4986451ad471097ea5eb67ca41da0f78ace809a6083aaa56343a4d11a5130"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6eadd9e2669e0d9fe09773972a3719d2e9d81d09"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "252ae3dd19168de2b6ba877ab21f6964ec3ed79e08d543714c832d9bf153b096"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a98ba7981bb66bae3e71e9b9874786532299c14"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "21bcc624bc031e8609a9c4cfebb4c7b9ec27f0e8f9ade764030b49bffdec1356"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "c326079bb22b87adbde590d5d78581662d77effe"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "93766ac7ac184c889eff925b5dfc65641b13a4b19b8a7d9f2b767f5fdcc6c353"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "c722ff486de7e5ce2bde6cce5cc4b546ec2ec296"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "d3084422a6bb4ef48b2c0e5ef4b2b03df462bbd1e1cec50d3e98a1893b2f3d19"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "bb825d6701c96fa2c502f82a966533ec99b1dbb6"
os = "windows"

    [[XZ.download]]
    sha256 = "4cf1e081e5cad7548dcba20fa70298bee76291fc884d36b3db50764c9ef99a7b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "538f0e086e56eafefcc1c3d106dbb3b1e0fab1ec"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "561a60607ac6443f92bd8c6c1618105aa93a3b69a50db041d1e3a20b1e83abd1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "riscv64"
git-tree-sha1 = "a46e089ca97e04f62131d7160f8a475bc9788282"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "f21f6f0d62d51590a8ffc78296c4ed823899c3928892b6e4ebb10ef24dd4eb43"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.riscv64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "2272cc406735a17ca23d9405c04ca25c232c1e6c"
os = "macos"

    [[XZ.download]]
    sha256 = "e96303d9c3c3b4d65d4834ec57d6a757a93d2806f032350e1237ba5fd274bd8f"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "45a076ac2b0b5e528159c96142254106709ec982"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "58069b3ba40bbbae0dce076a1cfde82919a2907f9e7dee581b07efdb728f13ce"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "98844b301ff9e4a93f4c681d78696eba0e8ba6b8"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "abdbb67f9c8551c17c40b6ed67cacf1dcbb6ae5262c274196bf8e4a40c8597fe"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "dc920f1d8d3b4ae2b795d11ad17622c4e87eae5b"
os = "freebsd"

    [[XZ.download]]
    sha256 = "e7d113725e6d481af6d629cc04d7b730c3948fca65bc8d766be4659f4ab6c664"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "004a4c653a5364f66fd8d8c2fe9c81f3fb5ae8fe"
os = "windows"

    [[XZ.download]]
    sha256 = "13aefb9bc61637721713f7fe9e955becec25f64045882cb2786ea457f9444989"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.8.1+0/XZ.v5.8.1.x86_64-w64-mingw32.tar.gz"
