[[XZ]]
arch = "aarch64"
git-tree-sha1 = "a6dd1ba35c9f4dcddf8199ec2ad4e413630f4e27"
os = "macos"

    [[XZ.download]]
    sha256 = "7c186e8c99fbf6cdbbb88078cc8e79175567d9abe94ca9c6db3f0bca0a034cbe"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "22e90a360b00419d28e3eea230738ed18b86134e"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "d8bcde6c7e8bf25d1becedc4d4166d67793cc5e019c1a5bfc5b376e03b74dfec"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "e2dbe2b3da24db36c14f5eed04353ff8c8448bc3"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "ac666ced5cc6f084c5200319e85c57bda47103f634d00290acc23862907967ba"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "396792d6d1099082b842db7be3b69ecfb2d51acd"
os = "freebsd"

    [[XZ.download]]
    sha256 = "5c9e9c171c578df70bfde0225ffafa1ba647dae79984aec248ff573587a5173c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.aarch64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a25f3c6e2ec5c7567ad638c769b475bee4a7aedd"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "f0a4bfad32e5aef9ac06e0e11280c093d90eb76ab1a2feeadb2cf60418f59f55"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af30f28d8c2de0a4d9fe5b1a519c7d5c47df3a0e"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "2c8e092c0fc61da83fb73770c57b6b58caa53d05e43f797c5cc45aad5a1f8b2c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67318c842da28b89d6d86d7c500f349ea67a9635"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "30491178d6e4968a6a671afbf414b693eae56c8f1fb539106f04680c123b250e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "634a9b4d7bb2c8978a0da2427768e3b904da9a1e"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "61482b7d9c61bf2ae81176d999038ecc676384648815148ecc22193c45c887ff"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "7d5ae8c3f0f3a481c1e9598c548f144668be1aad"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "021dec1eeb37f65d13a4c07dc377f595c9d85f9b74518e801167f565a6a6d81b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "26b8e732bfb560cc2901d559fbbe22252fe4f425"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "fc2741f601ed072dbb24921491c24b7e74453c32f1111d4f08bddd77deeda399"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "d601aba83ec681956ddf2c4b938668fc4d019fd0"
os = "windows"

    [[XZ.download]]
    sha256 = "42ce1b1a9aba13e050637af40d6931e3dd77310d7635e1452d6f48bcc8ef1d78"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "e3ac3b34aa647b8a6beaea9652627b70c62b9db9"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "cdeb2037864d0ad177bcc290319b0bf0785e137d2624d84fea1db89e85cfc6ea"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "riscv64"
git-tree-sha1 = "76f68b11b39a2ca0b55aba88268b266589367f07"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "4a207c21d46cb30d2c0d53aa015e7092e945001bc59f29614073494bc7d2bdad"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.riscv64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "29ba886f4c4f9f364811ed063daa266aa03d1081"
os = "macos"

    [[XZ.download]]
    sha256 = "0b3e6155bd600424f5f6c7fe0cec7ab12fdbb417a517b25c877ea85ab8b93b1d"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "d0faf13d05c6c21901264c2471cd5b9426162fe1"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "b0f37f230f482767a5a2aa8687a378db852514d3ed723540135c6c100071bc7c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "83426c2e17eddd75c98caf49bd9ffefdf8a1435f"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "76ee5849c30da7897c646654bbe39d1f00a4de564f2a47c0b054ee9c01cf57e7"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "fc13f23c138a6ae77141126c006f5bdbb0016f0b"
os = "freebsd"

    [[XZ.download]]
    sha256 = "279f76f2a484141f6e4e1a36e14e30fdcd95d542edb7db33acc41378eab7d166"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "cf64dd170a24141a8585b4d6564b8ffe1c9f407b"
os = "windows"

    [[XZ.download]]
    sha256 = "587cd5d34a0a8eca7bffec5968e25579991a98ff4c2a020ed310df952ebf305b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.4+1/XZ.v5.6.4.x86_64-w64-mingw32.tar.gz"
