[[XZ]]
arch = "aarch64"
git-tree-sha1 = "5d7ac54565aa955be0d3ff53c9ccebff5422f807"
os = "macos"

    [[XZ.download]]
    sha256 = "bf76016b6d5e5ffa88dabd4029bc83edf7b507803c2ca04dfabeab03f03bf584"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "14b57200fa9f5680679ac32d53cc43830361db2c"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "f2f832078873aed8b34becc42a1b051103f5aa8584aabdcb001ec677fa088815"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "0c84a9516e434d64da65fbb122ecad5dd43c830e"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "4cc12180b3bc532034957d4c45718a46508690635285dc4473168d4d7cebbe6a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ca17feb6718de0f247d81233f60f1fce8a7849b"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "b27c8dac93a500b34021efb1ec44d7905016d45e1c5a90ff5e08f1a1051f8df3"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4d2f74a53f7afa274c7e21474655c61051189c80"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "a8e08dd872b696c70c2cf16be7507ba54975eded6a455f0520f95363fa86ee9e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41367bba89011dbd46acc4e5fcab29ab3cf1203b"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "6fb896c485dc236b18d0f3439d3c23285ca62bf6d7e701e1e328a45cd08acea4"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e8c0f598f59e09f6633343364162624ac36e4f31"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "cefbde0c05d3245bd6d33e681f965cf0f8f7309f351fbbeeb8153f7b46a4d673"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "dc0f2d64e36eb4e25c2d67f3f081b0266a4d02b1"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "e745d405f3720d8acd599d868e26d372ff6ce4756449c35b814cca266c822e5a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "74f837fd7441d166469e9f775f22f8dc4361cc23"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "6c624a418e96268582a7a60642d17f98c5d0be8173ccb58ffb2b31e3f082973a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "d45961320aa2c58dd55bfa6080210fb0a601ce06"
os = "windows"

    [[XZ.download]]
    sha256 = "dbfe27742b606e6008bff6d05a7977075c134fcafeb6bec43e32aa56b8339b9b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "72a7a56fe85c469de1c4ccf029a4d6a961dd69f5"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "5df1de11ba4850c6666730ff7332a63da3701b6361d5e6c256bc2aa73f7220a5"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "2df309aba74e8da443b7cec62d80d84d6b9dc495"
os = "macos"

    [[XZ.download]]
    sha256 = "91a18bef9b15c4b97b40b01044006abb73581451812b6aa5723b30f5b81bcfb0"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "d6e550073d22b9b1976e67019e04eaa06f5f69f6"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "4943c6bdb474c52813ccdd4a226429b53097473ff696555be75c9dbda32e52dd"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "5cf70f0bf91dfcf8edabf7b98e7a700c7d4ded22"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "67ecacd7a7eff85bb3ee7584427abc8f3d7602d5c44fdbf8e226dbabc8217b0a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "1a72bb388a135729f66806371f6b7f9ee5e09908"
os = "freebsd"

    [[XZ.download]]
    sha256 = "4f91f2ce6d067071cbbd742afdc5ecab00683773b4b7785b0fada572d86de5ca"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "56fa03350be0023aabbb5b7303e043a90e285ac3"
os = "windows"

    [[XZ.download]]
    sha256 = "8b17c2533810e889c56a6b64d34667a60fbe16a3523d2b6c7a02b8b66786421a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.4.4+0/XZ.v5.4.4.x86_64-w64-mingw32.tar.gz"
