[[XZ]]
arch = "aarch64"
git-tree-sha1 = "1175500540bec2778f1856f7f44139146a140324"
os = "macos"

    [[XZ.download]]
    sha256 = "ce6d80d3092e2948574f1cea4197c8e9a8fedeb85a1c82fd3ad00bb85dd23490"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "ee0b42816521edcaad4b15de191f4f10647b89db"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "5f638c16c2cb117b6296c1dc45dd682463d6c2d9c548e2c1d2fb0c048e48bba0"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "1cfb2f0d0e832608b5b2ffb6d094b3d5958ce654"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "6c6f92bcc55227e425eadbe265e0c842e56eb0e8999e890d029a083d3a477540"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c2be7c40e3e6821404cd86dbce63db272146b75a"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "fb416547d3226b62a2f12105d5f9af46b7ad77469a6e0c5783527a78f8478d14"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de6c5c790f3a3f397d6dba03f7f5126660b4ffc7"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "8108055d20bbd51a16734fabbb8a1b08fa158a6b5a81dd215f73391a5c68a630"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e8b66fc1e159e1a83ccd65f38ae4f97b107a58e1"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "bf334bbbb7163bdc2b1f907ae6bb7618eed509c7e3e23093c02036cc345bebeb"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7706c3a456f2ebf1206f6f4a07c25dd7a5f788b5"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "23a8b242c74b5351330257020458bafbd09d67c5eccbaf9e85d75055119ee9fa"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "f5771fac5a7b90cfeee38fa75fa715fec6dcf4f4"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "480648a9a226339c8a33af82d711a21ac3fae9c5b30c9b4098c4b5c5236f0559"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "48afab41af883026c5e1f23abe4fe2d51b2169e9"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "50e1da7f7dc77a98cd3f857ffc5c5691227da682e266ae2d340d135cf27e8a85"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "036bbe370aafe44c2797730da0ccf0f573781e25"
os = "windows"

    [[XZ.download]]
    sha256 = "9408b4ac29de2d4af84dad130169ce39cf22bbba76f78044060e6f3cbda7776a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "c1d33797736667e08515045cfead91fd6c7c89ca"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "5beccfe669deee2a1f11e3431e7c0be1a166c34c2caab1a49f9b3c19a4a04a94"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "3082c61b20d5ec9ab3b71d270f209a751d4fb8f1"
os = "macos"

    [[XZ.download]]
    sha256 = "d7fcce844b016f79d1fca684a82957d51b7e52d1c5cbbaf2629ec1693f23085a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "cf38e2a484683868a98158cc6e4333e9417f8f45"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "52a0702ef222ce2d3b412549d6c6e6c19e0b10df8e66b115c71cfb8ef9fb578a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "ec3cdc7e7710f35a955e14c8f2a083dbfb30081c"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "66d386986aa087974475337de468bb4e99d2bfd858b2ef662768d781914f2f09"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "c4db016d1c2ab5f463497a4b12ac8614fe7988e3"
os = "freebsd"

    [[XZ.download]]
    sha256 = "a9f78431d7f0e9d9fbbefbca6a86fdbd12af3753636bd55429beafbf625ff20c"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "7c54f9b995a68be96c1adfe671c9deec79cf939d"
os = "windows"

    [[XZ.download]]
    sha256 = "3ebb80ece5d6b59da1f6dd1a21beb2d4e0fe5779641d1b6c10774b141479b005"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.7+0/XZ.v5.2.7.x86_64-w64-mingw32.tar.gz"
