[[XZ]]
arch = "aarch64"
git-tree-sha1 = "fcb5b558f5ea64a7eb7cb233bc302180797f44fc"
os = "macos"

    [[XZ.download]]
    sha256 = "ee68325dc69b0fa1e5287d363694202d01bcef97f7934ef9fe96479317628a79"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "eebec6378ffdd04e1bd489bb476db426ce97356b"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "9f2eb2ca2d7a63a0b54056ce2fefd8d8d554075a93f51d0a6068068252b790dc"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "2bf8773f9a8d6bc796a0b5f798c2751df97e06f8"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "0fb0117aaa61e8ca11fffba80bf63e4a8af3cf83e84f262c9dda4ed25bc6342d"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20aea1815a8cb825d8b30adfd6bfce8f237a333a"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "d8e5ef7d79174bb6436797132a3636518b47910a5d55e6fae913e72f05f75d0d"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cac152e7b26d29a9a6ce247e6884ac9dabf0a751"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "cb3d5e308244cbcc6ee55578b25eca47578df2d05d8f28aef5c9674d09fe243b"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a516170229e027f117c92651a2cc21517f2eda0c"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "e4f1a633d611493038e99627dcc850d4a96c4e5b52ec8ea5a951d7a4e543d339"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ade4a7efc5dee686a32ed4bc2d29cd763adf52b"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "24c2921f339b6493b2c110d105faef6a17883f101c970544e1941ccffa0cf1a1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "7dbc1ca6d60809e52adfa459470a5575a95bb3eb"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "71c4ecba925b89219f303ed4d46b2813cd81fd3a9eacd41ec2c25aa91ab74c55"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "72d55f597451190f95f1b5b375cf26bb468cb527"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "61ead39050e90bbaf74de285200dd402bb5465eeea6b608c0bfa6743ca06189a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "850193e2d166355bd5f5089024220dab3c08eb3f"
os = "windows"

    [[XZ.download]]
    sha256 = "64dd8f845c8012bf66f7be14254134623583644a1cd87027c398084c5a42bb5a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "f2ad7ee0f2d9955e4ef1957857da0525ea7a043e"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "a401872b015df9438fcb3f3654cfe2536c6bddb475ee62c518594e75d3b3396f"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "3ab716d0aa3677f640e26b09001561e81d9423c9"
os = "macos"

    [[XZ.download]]
    sha256 = "3196c7afbf7db11ffce6ca1556dfc76bdeb4215e32e0574383acf9a2134f9094"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "49d9387d0153ebcfb578e03cd2c58ddff2ef980b"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "0081d5df33e0e1aeabaa275a81e107ca46b70448ad74c2565b0b8bd26baa214e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "70a3d85be40afe56b025d40622f1ea8505504db5"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "acbd4a01483cd48b955034409cb6a5b219b8b1180b04ad7bfc20f14a3e29fdcc"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "94e6633f5c8f5fe46d2355b3374b24b7bb310bf0"
os = "freebsd"

    [[XZ.download]]
    sha256 = "e46abf62c674de843c75e25330f643a191835d39ac5c9b4e0298b454a097fd33"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "1e1dc537d7678969e1656f848e713fa8da760aaf"
os = "windows"

    [[XZ.download]]
    sha256 = "534d114af8a44e6bdf777924901c982d93a51bff4e7d7989610260765f5ff77e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.9+0/XZ.v5.2.9.x86_64-w64-mingw32.tar.gz"
