[[XZ]]
arch = "aarch64"
git-tree-sha1 = "df738267db7a923dbbd120955b5aa0d1df9af03d"
os = "macos"

    [[XZ.download]]
    sha256 = "43e189d62c199a1b2688d95c79ef377035d628a4b157c442b02f080e2c558963"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.aarch64-apple-darwin.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "c23a7470b69b2942d527c0441c9d11f66a50d1aa"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "4df400f3993bc8a765f7854f43815fec5c667e7882f0bdd8f47ad50dd4a38294"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "3b2b554d746952419a4d359725c79c5eb5517f3f"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "4321c0fa9621bee985f937baf8411318dd36fdb7a1fdcc0437c6a3b0db9aadc1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d79714ffb1c7a8fd7e483bd15a7b5439e22c5827"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "3d5b7faee7eb3dea0fe36c3261a67fa3aa0c3fbd55f24d71ea19cf1273af476a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.armv6l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94cb2da4c3044bce7a6046b1e2e3939025f4ec54"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "270e05d56852994cbe8a76db008b914ecb6ae831c2b5419f620a116e238c0a08"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.armv6l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a40405793db9dc9d907d351d89630b2ec7c8156"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "90a9e50efde57a97ebb5c46e33bf048b48cc13c58bde8a0be940cda94826dea0"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08a75f872e558b13b798c34b91429a2d7d53e4f2"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "738a8d97e49f42f6f884aad6ae42128f8e5a33f5bde53aa98f8e46c0b432e09f"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "17d18f29d648fed4aabace8e74beca8613a1381c"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "46ea1dfa99c3b8ddfffa86d85630374a9605848ffef2c440597756b96e758765"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "ebdcc2e9955242808a79e041696db5ee680b917f"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "add73ad815e26f0ae5ef848b3bacdf76bdb24cc886710b0c87e8b4eac2a1be19"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.i686-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "7050462507f16e7be71c37e256e9318e3d6fae55"
os = "windows"

    [[XZ.download]]
    sha256 = "bf902516b802a2774ecf2bf29b344a28177b5c246a4338da3cc9f89cd2b4be45"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "9e3b41134aa93a1da3f07b6d2c74583c8521a25a"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "d6e1d78e27590a1a62e9a521439507dbc617be7d84264250e3b70a16af4285af"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "5d72ca8088a4d7ea759db46e6a7f01222d3f273d"
os = "macos"

    [[XZ.download]]
    sha256 = "ac9912118c037127a3e3bb25351f5e68b756cd82c41e101db5901075040711cf"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.x86_64-apple-darwin.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "42eeaf7af67d068209a1e75e131f62bde480fb25"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "ac1c359c6cfa113ea95450ddecd5b622607bb6eec6b45f0a50226c62a1b74fc1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "06344d2738236cfc09cb9144b3650f00d2d682c1"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "79c52543b7592c16935f878e97ba7da3919c3323a397b5f9142a46575d627152"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "0ed6078f7261f6613418d23e4d413c4b4942750f"
os = "freebsd"

    [[XZ.download]]
    sha256 = "b6ed2ab8c06016e455838ac3498890a4633b38e00b25ab7009f1ba9c3f2ee6d1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.x86_64-unknown-freebsd.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "5b5b29b7893d534208563f2eed587df81318a779"
os = "windows"

    [[XZ.download]]
    sha256 = "5590a9a695982d8a5ba5be51ac3b73adfe0cb90671982ae35d7ca7eddfe56768"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.6.0+0/XZ.v5.6.0.x86_64-w64-mingw32.tar.gz"
