[[XZ]]
arch = "aarch64"
git-tree-sha1 = "1422e0e6ca4a8a05d2e725c099ffec390478b10a"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "1600815a9dea18ef208a65016be9763588fb9894adebcff5044c5802f7316c87"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "ac71b4e2bfa431119cce0847200bd778846356a3"
os = "windows"

    [[XZ.download]]
    sha256 = "71406df8e87f13e9e7521518b96490f8f5a5030051a78ee0182c5fcaa1664ea9"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "b14e2abb5397381b7886bda4ae9b3dc907fe98da"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "824fa979f3160cc70a0821ea54f7cd6ab249fb460416ef2f9ac5bde082005f54"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "d1d167130af12910a0a9c135f0d2656e931c3b56"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "640d0194958c5331e68fdeae1f9b32aadf14082084bd215b77c3585ae77496c8"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "armv7l"
git-tree-sha1 = "adc7e58c9e025e145cb2dd8866561ffb85992256"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "fe8361f410b5a2c07281d22ce291ee83e7b5c1a3d1bd7e3819fb81211f37575e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "ad549d724e3c5f513ba177bad97af9588a494a28"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "ab7de783c7ff3dc337c8acd7a98bfe72592d4dda60b57eef58e11313e2388d3f"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "1144ee0a38bef2ce420530376ab94c4a6cf83380"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "47a3dbe02e0a281dc22ae4893d114be2f28fb190ea4463e744060be1d4c0ab2a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "0ca2d2c9d10de4d0083dd15558bfbb9c4bafdc23"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "0af3b9bbe656b8586dcd17c7da7bd1a08b4b02bd35eb80a63c1bb96e789a138d"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "345bfce3e3bea686b586a7d4e96c73e0754a6f5a"
os = "macos"

    [[XZ.download]]
    sha256 = "c7111a77493e69516c5c36e253f837dfcb2335fbc943d10e289d16d13b231a15"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.x86_64-apple-darwin14.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "e4d8cd43ffbb7a8c53284fbbf30dc75a1d9c6b82"
os = "freebsd"

    [[XZ.download]]
    sha256 = "8140496493aa58d2eea5472b0f41d812a6e6b8678f420a7e84faa08e2be175fc"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.x86_64-unknown-freebsd11.1.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "3b6676b41ddde754f60212fdd48d1294c6f11e70"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "fa4d109b168a031472eaa8469fe1106af70b1fe6e0cafd7959f04f1dd1cca716"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.i686-linux-musl.tar.gz"
[[XZ]]
arch = "armv7l"
git-tree-sha1 = "1431fef6f97e547615ec27b9caabb8d330bcabbc"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "833d9f093b004453cd4ddfdeb298ee1be39da4fe4cf82d488c82a1004c5cf928"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "543ffebe7412632b09da4e64fc61551afbcbde07"
os = "windows"

    [[XZ.download]]
    sha256 = "6d79a1d78bfab3dd15fb656b4445389018aa5cd0ccdc62c71704a15401e6fecb"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+3/XZ.v5.2.4.x86_64-w64-mingw32.tar.gz"
