[[XZ]]
arch = "aarch64"
git-tree-sha1 = "026acda59d4914ecc8f53a3d99c7569de824d5fb"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "a063f9847b9da3be946f50f16ed692da10546020266b81d435ec5803eeadaee8"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.aarch64-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "d5c06349e031167ab6799216ffbf00d4b080a74d"
os = "windows"

    [[XZ.download]]
    sha256 = "ea352f25b9dacff7c4925346d3ab218f53f3c6e00cd546a48a0b6ca63c8a80bb"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.i686-w64-mingw32.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "5dc6a152b337d31187841acd7d3f961ea0ca00ee"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "b5b24ab90fa64f542dde78043202f15d276f1994a015b22c841b85271c79bc8a"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.x86_64-linux-musl.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "106f24d95babfa229781555c8e7891f5f2c82ec4"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "2b7d42f70897e3de3f1bb68a4c8e926ee708c1b9d88bb8c75455932e3223ff64"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.i686-linux-gnu.tar.gz"
[[XZ]]
arch = "armv7l"
git-tree-sha1 = "d3911add65ae743a704c9e49702bdf0d6be9e319"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "ef15f272f180544344513715652b233bff1b74c0f28dd3c2b1616a51cc676ffc"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.armv7l-linux-gnueabihf.tar.gz"
[[XZ]]
arch = "aarch64"
git-tree-sha1 = "b6956ad07cba844efd39f43cd77406a923b74cb2"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "134b1700e79bfed60f501ff18ea2679ebf41cbea9da14109da3ffd7906257d25"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.aarch64-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "224d5c80062c875f71f1060f34c825a9ac44fe1b"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "8e6553aa7d431ca7c56ec24563e1349931c68dcb8d14d6adc44ef5aecae2851e"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.x86_64-linux-gnu.tar.gz"
[[XZ]]
arch = "powerpc64le"
git-tree-sha1 = "e900bfb6b6772509e8e4322f05ed9e1ba266f538"
libc = "glibc"
os = "linux"

    [[XZ.download]]
    sha256 = "cb7f67b3b5beb91be4c81d5bd8504c38bbd38fb3774b35b3d4e545215e1d2059"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.powerpc64le-linux-gnu.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "68141b4c338d4c8c9f5a9d97c1e958dcfe7cff7e"
os = "macos"

    [[XZ.download]]
    sha256 = "229d962af013d9c73ea1d6c892142836d7bcaf286dfb5a18fb1347ef4e60c410"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.x86_64-apple-darwin14.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "6ae8dd4bb9b4bed92f1c30f4f4148375a063bb43"
os = "freebsd"

    [[XZ.download]]
    sha256 = "c993d890f07be3c38df985a82759873726ed7076166a9896b24f0865a9dedaa2"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.x86_64-unknown-freebsd11.1.tar.gz"
[[XZ]]
arch = "i686"
git-tree-sha1 = "846b78438779967ebc2d406bcc1e0f1ae921d2b8"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "5cf44667613050a187616402f2cad0e63421f9a23ad2eb8e8189280e2446d391"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.i686-linux-musl.tar.gz"
[[XZ]]
arch = "armv7l"
git-tree-sha1 = "bed7ce0514be3b063d237544012e16298ba8067b"
libc = "musl"
os = "linux"

    [[XZ.download]]
    sha256 = "d204932d048f46947bda2e635ae8bf26274e0e7f056c5aded9b4a529fac786d1"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.armv7l-linux-musleabihf.tar.gz"
[[XZ]]
arch = "x86_64"
git-tree-sha1 = "6342e5e66dc624a618d6f46623dcf131b034995a"
os = "windows"

    [[XZ.download]]
    sha256 = "04bdd20b4ef42ce31f4c8325a4995524d4e5449d76d1a3847ee49ca0934005f9"
    url = "https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases/download/XZ-v5.2.4+2/XZ.v5.2.4.x86_64-w64-mingw32.tar.gz"
